### ISSUE TITLE
Light levels too high

### ISSUE THREAD

**Issue by Ideki** [SongXia-NYU/castle_in_the_sky#10]
The problem is that the castle was built for 1.17 when the mob would spawn at light level less than 7.

With the change to spawning mechanics in 1.18, a lot of corridors and rooms have already too much light by default.

So it is very hard to get mobs to spawn and the required keys to progress.
We did 3 castles so far on our server and each time we had difficulties to open the first few yellow doors.
And it is not a drop-rate issue, just a spawn rate.

I would suggest reducing the light further in the corridors.
Make them togglable like you did in most place.

Also, the spaces between the walls need to be filled to avoid mobs spawning in them which reduce even further the spawn rate in the corridors and room.

**Comment by SongXia-NYU** [comment]
Thanks. Working on it

**Comment by SongXia-NYU** [comment]
Fixed in 0.3.2
Let me know if I miss some places in the castle :)

**Comment by Ideki** [comment]
Castle is darker in the corridors.

I still think you should either fill the walls, or add light.
Especially above corridors and flat surfaces.
I can still see mobs spawning there and that impact the spawners.
Quit a few times I was standing under or next to the spawner and nothing would come out.
Other times it would spawn 4 mobs.

Also maybe increase the spawner check radius in case you changed it.
Because it feels like I need to be right under it for it to start working.
If I move 4-5 blocks away, the spawner does not show the small flames indicating that it is active.

**Comment by Ideki** [comment]
![image](https://user-images.githubusercontent.com/18094701/150164156-740dfdbd-094b-4918-b454-ba2df74e6153.png)

**Comment by Ideki** [comment]
Some corridors (especially when going to level 2-3 (the deepest) seems to have to much light.

You can check the F3 info, under the spawner light level is 7, so the spawner would never work:

![image](https://user-images.githubusercontent.com/18094701/150165152-4f36ecea-2a8e-4b6b-9c42-9ff86b34a7d8.png)

**Comment by Ideki** [comment]
nvm, CurseForge messed up the version.
It had downloaded the latest version but was still using the previous one. :/
