### ISSUE TITLE
Creeper blast

### ISSUE THREAD

**Issue by Ideki** [SongXia-NYU/castle_in_the_sky#11]
I suggest that you make the castle creeper-blast resistant.
The reason are:

- We can use creepers to bypass doors-keys completely by making them explode where we need.
- Creepers destroy the castle itself and it is near impossible to rebuild it to look like what you did. Which is a shame considering the amount of work you put into it and how beautiful it is.
- Creeper blast can trigger water damage in some sections that can damage the redstone circuits. Which in turn prevents us to open treasure boxes.

There are ways to prevent mobs damage, some mods like Flan (https://www.curseforge.com/minecraft/mc-mods/flan-forge) prevent creeper blasts damage inside player defined zones.

**Comment by SongXia-NYU** [comment]
I initially disabled creeper in the castle but for some reason it does not work in 1.18.
I will fix the bug. Thanks.

**Comment by SongXia-NYU** [comment]
Fixed in 0.3.2

**Comment by Ideki** [comment]
I can still see creepers.

I am using Xaero's minimap, and I see creepers around me.
Not in the corridors so far, so probably outside the walls.
Or I might just be lucky to have seen none inside the corridors yet.

**Comment by Ideki** [comment]
You can see the creepers in the minimap top-left corner:

![image](https://user-images.githubusercontent.com/18094701/150164384-bc772a07-32f4-4140-ac3f-0550022ab1bf.png)
